config:
  name: default
  seed: 42
  device: cuda
  num_workers: 0
  root_dir: ./ # project root dir
  dataset_dir: ./dataset/ # dataset dir
  output_dir: ./output/ # output dir
  mesh_file: ./dataset/mesh_cylinder_lam.su2 # mesh file
  variable: ['VELOCITY-X', 'VELOCITY-Y'] # based on SU2 output docs

model:
  convolution_layers:
    type: GMMConv # [GMMConv, ChebConv, GCNConv, GATConv]
    hidden_channels: [128, 128, 128]
    act: relu
    dropout: 0.1 # probability
    kernel_size: 5
    K: 5
    dim: 1
    ffn: 128
    bottleneck: 128

  encoder:
    hidden_channels: [128, 128, 128]  # for GNN
    bottleneck: 128  # output dimension of GNN and input dimension of MLP
    ffn: [128, 128, 128]  # for MLP
    act: relu
    conv: GMMConv
    graph_pooling: TopKPooling

  decoder:
    hidden_channels: [128, 128, 128]  # for GNN
    bottleneck: 128 # output dimension of MLP and input dimension of GNN
    ffn: [128, 128, 128]  # for MLP
    act: relu
    conv: GMMConv
    graph_pooling: TopKPooling


training:
  epochs: 100
  batch_size: 128
  print_train: 10
  
  optimizer:
    type: Adam # [Adam, AdamW]
    learning_rate: 0.001
    weight_decay: 0.0001

  scheduler:
    type: StepLR # [StepLR, CosineAnnealingLR]
    step_size: 10
    gamma: 0.1

  early_stopping:
    early_stopping: 10
    patience: 10

  loss:
    loss: RMSE # [MSELoss, RMSE]

  metric:
    metric: RMSE # [MSE, RMSE]


