config:
  name: default
  seed: 42
  device: cuda
  num_workers: 0
  root_dir: ./ # project root dir
  dataset_dir: ./dataset/cylinder_vonkarman/Re200_cut/flow # dataset dir
  split_dir: ./dataset/cylinder_vonkarman/Re200_cut/flow_split # split dir
  output_dir: ./output/ # output dir
  mesh_file: D:\TA\TA2\GAE-ROM\dataset\cylinder_vonkarman\Re200_cut\cylinder_D04
  variable: velocity # ['VELOCITY-X', 'VELOCITY-Y'] # based on SU2 output docs
  data_sample: 20 # number of data samples to use for training

model:
  convolution_layers:
    type: ChebConv # [GMMConv, ChebConv, GCNConv, GATConv]
    hidden_channels: [64, 64, 64]
    act: relu
    dropout: 0.1 # probability
    kernel_size: 5
    K: 5
    dim: 2
    ffn: 64
    bottleneck: 64

  encoder:
    hidden_channels: [128, 128, 64]  # Reduced from [256, 256, 128]
    bottleneck: 64  # Reduced from 128
    ffn: [64, 64, 25]  # Reduced from [128, 128, 25]
    act: relu
    conv: GMMConv
    dim: 1
    graph_pooling: TopKPooling

  autoencoder:
    input_dim: 25
    encoder_layers: [25, 100, 100, 100, 100, 2]
    decoder_layers: [2, 100, 100, 100, 100, 25]
    latent_dim: 2
    act: relu
    dropout: 0.1 # probability

  decoder:
    hidden_channels: [64, 128, 128]  # Reduced from [128, 256, 256]
    bottleneck: 64  # Reduced from 128
    ffn: [25, 64, 64]  # Reduced from [25, 128, 128]
    act: relu
    conv: GMMConv
    dim: 1
    graph_pooling: TopKPooling


training:
  epochs: 100
  batch_size: 1
  print_train: 10

  optimizer:
    type: Adam # [Adam, AdamW]
    learning_rate: 0.001
    weight_decay: 0.0001

  scheduler:
    type: StepLR # [StepLR, CosineAnnealingLR]
    step_size: 10
    gamma: 0.1

  early_stopping:
    early_stopping: 10
    patience: 10

  loss:
    loss: RMSE # [MSELoss, RMSE]

  metric:
    metric: RMSE # [MSE, RMSE]


